### ISSUE TITLE
When is it supposed to be completed? 

### ISSUE THREAD

**Issue by Talhamehar007** [DarkSecDevelopers/Pyrat#1]
I've been seeing this repository for a long time , under development, but haven't uploaded anything yet. Are you working on this project or not? And when is it expected to be completed? I've been eagerly waiting for this!

**Comment by usama7628674** [comment]
@Talhamehar007 I've been busy lately and will start working on it soon.

**Comment by sTiKyt** [comment]
@Talhamehar007 someday, sometime xD You can always contribute to speed process up
